version: '2'
services:
    common_env_pro:
        environment:
            FLASK_APP_SETTINGS: "/etc/web/flask.conf.py"
            ALL_SERVICES_SETTINGS: ".pro"
            BACKEND_AWS_ACCESS_KEY_ID:
            BACKEND_AWS_SECRET_ACCESS_KEY:
            CRAWLER_PASSWORD:
            NOTIFICATION_EMAIL_PASSWORD:
            PYTHONHASHSEED:
            S3_BUCKET:
            SECRET_KEY:
