version: '2'
volumes:
    git: {}
    log: {}
    sql: {}
    
services:
    web:
      extends:
        service: webserver
        file: web-service-dev.yml
      expose:
       - "5000"

    cache:
      extends:
        service: webserver
        file: web-service-dev.yml
      expose:
       - "5000"
      command: ["/venv/web/bin/python", "-m", "rebase.scripts.cache"]

    scheduler:
      extends:
        service: webserver
        file: web-service-dev.yml
      command: ["/venv/web/bin/python", "-m", "rebase.scripts.scheduler"]

    jupyter:
      extends:
        service: webserver
        file: web-service-dev.yml
      image: rebase/jupyter
      ports:
       - "8888:8888"
      volumes_from:
       - rq_default

    app:
      image: rebase/client
      environment:
          REBASE_CLIENT_HOST: "dev"
          REBASE_CLIENT_PORT: 3000
      ports:
       - "3000:3000"
      volumes:
       - ../../../react-app:/code
      extends:
        service: common_env
        file: web-service-dev.yml

    code2resume:
        image: rebase/client
        environment:
          REBASE_CLIENT_HOST: "dev"
          REBASE_CLIENT_PORT: 3001
        ports:
         - "3001:3001"
        volumes:
         - ../../../react-app:/code
        extends:
          service: common_env
          file: web-service-dev.yml
        command: ["/code/start", "code2resume"]

    javascript:
        image: rebase/javascript
        expose:
            - "7777"

    parser:
        image: rebase/dev-parser
        expose:
            - "1111"
        volumes:
            - ../../../parser:/parser

    rq_population:
      extends:
        service: webserver
        file: web-service-dev.yml
      image: rebase/dev-rq-population
      environment:
        SETTINGS: ".population.dev"

    rq_git:
      extends:
        service: webserver
        file: web-service-dev.yml
      image: rebase/dev-rq-git
      ports:
       - "2222:22"
      volumes:
       - git:/git

    rq_default:
      extends:
        service: webserver
        file: web-service-dev.yml
      image: rebase/dev-rq-default
      environment:
        SETTINGS: ".rq_default.dev"
        CRAWLER_USERNAME:
        CRAWLER_PASSWORD:
      tmpfs:
       - /repos:rw,noexec,size=3g

    rq_dashboard:
        image: rebase/rq_dashboard
        ports:
         - "4444:4444"

    redis:
      image: redis
      restart: always

    database:
      image: postgres
      environment:
        PGDATA: "/var/lib/postgresql/data/rebase"
      volumes:
       - sql:/var/lib/postgresql/data/rebase

    rsyslog:
      image: rebase/rsyslog
      volumes:
       - log:/var/log
