version: '2'
volumes:
    git: {}
    log: {}
    sql: {}
    
services:
    web:
      image: rebase/pro-web
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
          SETTINGS: ".web.pro"

    cache:
      image: rebase/pro-web
      command: ["/venv/web/bin/cache"]
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
          SETTINGS: ".web.pro"

    scheduler:
      image: rebase/pro-web
      command: ["/venv/web/bin/python", "-m", "rebase.scripts.scheduler"]
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml

    app:
      image: rebase/client
      environment:
          REBASE_CLIENT_HOST: "dev"
          REBASE_CLIENT_PORT: 3000
      ports:
       - "3000:3000"
      volumes:
       - ../../../react-app:/code

    code2resume:
        image: rebase/client
        environment:
          REBASE_CLIENT_HOST: "dev"
          REBASE_CLIENT_PORT: 3001
        ports:
         - "3001:3001"
        volumes:
         - ../../../react-app:/code
        command: ["/code/start", "code2resume"]

    javascript:
        image: rebase/javascript

    parser:
        image: rebase/pro-parser

    rq_default:
      image: rebase/pro-rq-default
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
        SETTINGS: ".rq_default.pro"
        CRAWLER_USERNAME:
        CRAWLER_PASSWORD:
      tmpfs:
       - /repos:rw,noexec,size=3g

    rq_population:
      image: rebase/pro-rq-population
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
        SETTINGS: ".population.pro"

    rq_git:
      image: rebase/pro-rq-git
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      ports:
       - "2222:22"
      volumes:
       - git:/git

    jupyter:
      image: rebase/jupyter
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      ports:
       - "8888:8888"

    rq_dashboard:
        image: rebase/rq_dashboard
        ports:
         - "4444:4444"

    redis:
      image: redis
      restart: always

    database:
      image: postgres
      environment:
        PGDATA: "/var/lib/postgresql/data/rebase"
      volumes:
       - sql:/var/lib/postgresql/data/rebase

    rsyslog:
      image: rebase/rsyslog
      volumes:
       - log:/var/log
