version: '2'
volumes:
    etc_letsencrypt: {}
    git: {}
    log: {}
    repos: {}
    sql: {}
    www: {}

services:
    web:
      image: rebase/pro-web
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
          SETTINGS: ".web.pro"

    cache:
      image: rebase/pro-web
      command: ["/venv/web/bin/cache"]
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
          SETTINGS: ".web.pro"

    scheduler:
      image: rebase/pro-web
      command: ["/venv/web/bin/python", "-m", "rebase.scripts.scheduler"]
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml

    app:
        image: rebase/client
        volumes:
            - ../react-app:/code
            - www:/www
        command: ["/code/init", "app"]

    code2resume:
        image: rebase/client
      volumes:
       - ../react-app:/code
       - www:/www
      command: ["/code/init", "code2resume"]

    ycdemo:
        image: rebase/pro-client
        volumes:
            - ../react-app:/code
           - www:/www
        stdin_open: true
        tty: true
        command: ["/bin/sh"]

    javascript:
        image: rebase/javascript

    parser:
        image: rebase/pro-parser

    rq_default:
      image: rebase/pro-rq-default
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      volumes:
       - repos:/repos
      environment:
        SETTINGS: ".rq_default.pro"
        CRAWLER_USERNAME:
        CRAWLER_PASSWORD:

    rq_population:
      image: rebase/pro-rq-population
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
        SETTINGS: ".population.pro"

    rq_git:
      image: rebase/pro-rq-git
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      ports:
       - "22:22"
      volumes:
       - git:/git

    jupyter:
      image: rebase/jupyter
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      ports:
       - "8888:8888"

    rq_dashboard:
        image: rebase/rq_dashboard
        ports:
         - "4444:4444"

    nginx:
        image: rebase/nginx
        ports:
         - 80:80
         - 443:443
        volumes:
         - etc_letsencrypt:/etc/letsencrypt
         - www:/www:ro

    redis:
      image: redis
      restart: always

    database:
      image: postgres
      environment:
        PGDATA: "/var/lib/postgresql/data/rebase"
      volumes:
       - sql:/var/lib/postgresql/data/rebase

    rsyslog:
      image: rebase/rsyslog
      volumes:
       - log:/var/log

