version: '2'
volumes:
    etc_letsencrypt: {}
    log: {}
    sql: {}

services:

    web:
      image: alpha.rebaseapp.com:5000/rebase/pro-web
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
        SETTINGS: ".web.pro"
        GITHUB_APP_ID:
        GITHUB_APP_SECRET:
        GITHUB_CODE2RESUME_ID:
        GITHUB_CODE2RESUME_SECRET:

    javascript:
        image: alpha.rebaseapp.com:5000/rebase/javascript

    parser:
        image: alpha.rebaseapp.com:5000/rebase/pro-parser

    impact_python:
        image: alpha.rebaseapp.com:5000/rebase/pro-impact-python
    
    impact_javascript:
        image: alpha.rebaseapp.com:5000/rebase/pro-impact-javascript

    rq_default:
      image: alpha.rebaseapp.com:5000/rebase/pro-rq-default
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
        SETTINGS: ".rq_default.config"
        CRAWLER_USERNAME:
        CRAWLER_PASSWORD:
        GITHUB_APP_ID:
        GITHUB_APP_SECRET:
        GITHUB_CODE2RESUME_ID:
        GITHUB_CODE2RESUME_SECRET:
        # make sure the following number matches the tmpfs size
        REPOS_VOLUME_SIZE_IN_MB: 3072
        # if REPOS_VOLUME_SIZE_IN_MB is less than 10MB, factor should be 10
        # if REPOS_VOLUME_SIZE_IN_MB is less than 100MB, factor should be 3
        # if REPOS_VOLUME_SIZE_IN_MB is less than 1000MB, factor should be 2
        CLONE_SIZE_SAFETY_FACTOR: 2
      tmpfs:
       - /repos:rw,noexec,size=3g

    github_public_crawling:
        extends: rq_default
        environment:
            SETTINGS: ".github_public_crawling.config"

    rq_population:
      image: alpha.rebaseapp.com:5000/rebase/pro-rq-population
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      environment:
        SETTINGS: ".population.pro"

    jupyter:
      image: alpha.rebaseapp.com:5000/rebase/jupyter
      extends:
        service: common_env_pro
        file: common-python-service-environment.pro.yml
      ports:
       - "8888:8888"

    rq_dashboard:
        image: alpha.rebaseapp.com:5000/rebase/rq_dashboard
        ports:
         - "4444:4444"

    nginx:
        image: alpha.rebaseapp.com:5000/rebase/pro-nginx
        ports:
         - 80:80
         - 443:443
        volumes:
         - etc_letsencrypt:/etc/letsencrypt

    redis:
      image: redis
      restart: always

    database:
      image: postgres
      environment:
        PGDATA: "/var/lib/postgresql/data/rebase"
      volumes:
       - sql:/var/lib/postgresql/data/rebase

    rsyslog:
      image: alpha.rebaseapp.com:5000/rebase/rsyslog
      volumes:
       - log:/var/log

