web:
  image: rebase/api
  ports:
   - "5000:5000"
  volumes:
   - .:/api
  links:
   - redis
   - database:db
redis:
  image: redis
  restart: always
database:
  image: postgres
client:
  build: ../react-app
  ports:
   - "3000:3000"
  volumes:
   - ../react-app:/code
  links:
   - web
  command: bash -c "npm start"
rq_git:
  image: rebase/rq_git
  volumes:
   - .:/api
  links:
   - redis
   - database:db
  ports:
   - "2222:22"
rq_default:
  image: rebase/api
  volumes:
   - .:/api
  links:
   - redis
   - database:db
  command: ["bash", "-c", "source /venv/api/bin/activate && python run-worker.py"]
