web:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - .:/api
  links:
   - redis
   - database:db
redis:
  image: redis
  restart: always
database:
  image: postgres
client:
  build: ../react-app/
  ports:
   - "3000:3000"
  volumes:
   - ../react-app:/code
  links:
   - web
  command: bash -c "npm install && npm start"
rq_git:
  build: .
  volumes:
   - .:/api
  links:
   - redis
   - database:db
  command: bash -c "pip install -r requirements.txt; python git-worker.py"
rq_default:
  build: .
  volumes:
   - .:/api
  links:
   - web
   - redis
   - database:db
  command: bash -c "pip install -r requirements.txt; python run-worker.py"
git:
  build: ./git/Dockerfile

