web:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - .:/api
  links:
   - redis
   - database:db
redis:
  image: redis
database:
  image: postgres
client:
  build: ../react-app/
  ports:
   - "3000:3000"
  volumes:
   - ../react-app:/code
  links:
   - web
  command: bash -c "npm install && npm start"
  stdin_open: true
  tty: true
