web:
  image: rebase/api
  ports:
   - "${API_PORT}:5000"
  volumes:
   - .:/api
  links:
   - redis
   - database:db
redis:
  image: redis
  restart: always
database:
  image: postgres
client:
  build: ../react-app
  ports:
   - "${WEBPACK_PORT}:3000"
  volumes:
   - ../react-app:/code
  links:
   - web
  environment:
    WEBPACK_HOST: "${WEBPACK_HOST}"
    WEBPACK_PORT: "${WEBPACK_PORT}"
  command: bash -c "npm install && npm start"
rq_git:
  image: rebase/rq_git
  volumes:
   - .:/api
  links:
   - redis
   - database:db
  ports:
   - "${GIT_PORT}:22"
rq_default:
  image: rebase/api
  volumes:
   - .:/api
  links:
   - redis
   - database:db
  command: ["bash", "-c", "source /venv/api/bin/activate && python run-worker.py"]
