web:
  image: rebase/api
  ports:
   - "${API_PORT}:5000"
  volumes:
   - .:/api
  links:
   - redis
   - database:db
  environment:
    REBASE_HOST: "${REBASE_HOST}"
    REBASE_PORT: "${REBASE_PORT}"
redis:
  image: redis
  restart: always
database:
  image: postgres
client:
  build: ../react-app/
  ports:
   - "${REBASE_PORT}:3000"
  volumes:
   - ../react-app:/code
  links:
   - web
  environment:
    WEBPACK_HOST: "${REBASE_HOST}"
    WEBPACK_PORT: "${REBASE_PORT}"
rq_git:
  image: rebase/rq_git
  volumes:
   - .:/api
  links:
   - redis
   - database:db
  ports:
   - "${GIT_PORT}:22"
  environment:
    REBASE_HOST: "${REBASE_HOST}"
    REBASE_PORT: "${REBASE_PORT}"
rq_default:
  image: rebase/api
  volumes:
   - .:/api
  links:
   - redis
   - database:db
  environment:
    REBASE_HOST: "${REBASE_HOST}"
    REBASE_PORT: "${REBASE_PORT}"
  command: ["/venv/api/bin/python", "run-worker.py"]
nginx:
    build: nginx
    ports:
     - "8080:80"
    links:
     - web
    volumes_from:
     - client:ro
