web:
  extends:
    service: webserver
    file: docker/api-production.yml
  links:
   - redis
   - database:db
  command: ["/venv/api/bin/gunicorn", "-c", "/api/etc/gunicorn.pro.conf", "wsgi:app"]

client:
  image: rebase/client-production
  volumes:
   - ../react-app:/code
  extends:
    service: common_env
    file: docker/api-production.yml

rq_git:
  extends:
    service: webserver
    file: docker/api-production.yml
  image: rebase/rq_git
  links:
   - redis
   - database:db
  ports:
   - "2222:22"

rq_default:
  extends:
    service: webserver
    file: docker/api-production.yml
  links:
   - redis
   - database:db
  command: ["/venv/api/bin/python", "run-worker.py"]

nginx:
    build: nginx
    ports:
     - "${REBASE_CLIENT_PORT}:80"
    links:
     - web
    volumes_from:
     - client:ro

redis:
  image: redis
  restart: always

database:
  image: postgres
