web:
  extends:
    service: webserver
    file: docker/api-production.yml
  links:
   - redis
   - database:db
   - rsyslog
  command: ["/venv/api/bin/gunicorn", "-c", "/api/etc/gunicorn.pro.conf", "wsgi:app"]

cache:
  extends:
    service: webserver
    file: docker/api-production.yml
  links:
   - redis
   - database:db
   - rsyslog
  command: ["/api/cache"]

scheduler:
  extends:
    service: webserver
    file: docker/api-production.yml
  links:
   - database:db
   - rsyslog
  command: ["/venv/api/bin/python", "scheduler.py"]

client:
  image: rebase/client
  volumes:
   - ../react-app:/code
   - www:/www
  extends:
    service: common_env
    file: docker/api-production.yml
  command: ["/code/init"]

rq_git:
  extends:
    service: webserver
    file: docker/api-production.yml
  image: rebase/rq_git
  ports:
   - "2222:22"
  links:
   - database:db
   - redis
   - rsyslog
  volumes:
   - git:/git

rq_default:
  extends:
    service: webserver
    file: docker/api-production.yml
  links:
   - cache
   - database:db
   - redis
   - rsyslog
  command: ["/venv/api/bin/python", "run-worker.py"]

nginx:
    build: nginx
    ports:
     - "${REBASE_CLIENT_PORT}:80"
    links:
     - web
    volumes_from:
     - client:ro

redis:
  image: redis
  restart: always

database:
  image: postgres
  environment:
    PGDATA: "/var/lib/postgresql/data/rebase"
  volumes:
   - sql:/var/lib/postgresql/data/rebase

rsyslog:
  image: rebase/rsyslog
  volumes:
   - log:/var/log
