#!/bin/bash

pushd .

# let's activate the build virtual environment

source /venv/build/bin/activate

# First fetch wheel and build c extensions

pip wheel \
    --find-links /wheelhouse/wheels \
    --requirement docker/web/requirements.txt \
    --wheel-dir=/wheelhouse/wheels

# Now let's make a Dockerfile context
# we can't symlink wheels into the 'source' directory 'docker/web'
# because are not repeatable across machines and hence not supported by Docker.
# Instead, we just make hard copies of everything we need to build a container into a separate
# directory ('/tmp/web'), build the container, and finally, wipe the build dir.

mkdir -p /tmp/web

cp docker/web/dev-Dockerfile /tmp/web/Dockerfile

cp docker/web/requirements.txt /tmp/web/requirements.txt

cp -r /wheelhouse/wheels /tmp/web/.

docker build -t rebase/dev-web /tmp/web

rm -rf /tmp/web

deactivate

popd
