#!/bin/bash

pushd .

# let's activate the build virtual environment

source /venv/build/bin/activate

# First fetch wheel and build c extensions

pip wheel \
    --find-links /wheelhouse/wheels \
    --requirement docker/web/requirements.txt \
    --wheel-dir=/wheelhouse/wheels

# Now let's make a Dockerfile context
# we can't symlink wheels into the 'source' directory 'docker/web'
# because are not repeatable across machines and hence not supported by Docker.
# Instead, we just make hard copies of everything we need to build a container into a separate
# directory ('/tmp/web'), build the container, and finally, wipe the build dir.

rm -rf /tmp/web/
mkdir -p /tmp/web/build

# build the 'web' wheel:
python docker/web/setup.py \
    build \
        -b /tmp/web/build/ \
    bdist_wheel \
        -d /wheelhouse/wheels/ \
    egg_info \
        -e /tmp/web

cp docker/web/pro-Dockerfile /tmp/web/Dockerfile

cp rebase/common/pro.py /tmp/web/flask.conf.py

cp etc/gunicorn.pro.conf /tmp/web/gunicorn.pro.conf

cp -r /wheelhouse/wheels /tmp/web/.

docker build -t rebase/pro-web /tmp/web

docker tag rebase/pro-web alpha.rebaseapp.com:5000/rebase/pro-web

rm -rf /tmp/web

deactivate

popd
