"""Add hidden boolean to Ticket model

Revision ID: 97460253da53
Revises: 
Create Date: 2016-04-05 19:29:26.223626

"""

# revision identifiers, used by Alembic.
revision = '97460253da53'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('hidden', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'hidden')
    ### end Alembic commands ###
