version: '2'
services:
    common_env_pro:
      environment:
        APP_SETTINGS: "/settings/pro.py"
        BACKEND_AWS_ACCESS_KEY_ID:
        BACKEND_AWS_SECRET_ACCESS_KEY:
        CRAWLER_PASSWORD:
        GITHUB_APP_SECRET:
        GITHUB_CODE2RESUME_SECRET:
        NOTIFICATION_EMAIL_PASSWORD:
        PYTHONHASHSEED:
        S3_BUCKET:
        SECRET_KEY:
