#!/bin/bash

# can't mount a symlinked dir like /tmp
build_dir=~/.rebase/build/nginx
www_dir=$build_dir/www

rm -rf $build_dir
mkdir -p $www_dir

docker build -t rebase/client ../react-app 
docker run --rm -it -v $www_dir:/www -v $PWD/../react-app:/code rebase/client /code/init code2resume
docker run --rm -it -v $www_dir:/www -v $PWD/../react-app:/code rebase/client /code/init app

pushd docker/nginx
cp pro-Dockerfile $build_dir/Dockerfile
cp local-pro-Dockerfile $build_dir
cp nginx.conf $build_dir
cp default-443.conf $build_dir
cp default-80.conf $build_dir
cp default-3000.conf $build_dir
cp nginx-ssl.conf $build_dir
cp api_proxy.conf $build_dir
cp api_proxy_local.conf $build_dir
cp listen.bash $build_dir
popd

pushd $build_dir
docker build -t rebase/pro-nginx .
docker build -t rebase/local-pro-nginx -f local-pro-Dockerfile .
popd

