#! /usr/bin/env python

from os import environ
from os.path import exists, join
from subprocess import call
from sys import argv, exit


with open('/tmp/filter', 'w') as f:
    f.write(str(argv)+'\n')
    pass


valid_commands = ['git-receive-pack', 'git-upload-archive', 'git-upload-pack']

if len(argv) != 3:
    exit(6)
if len(argv[2]) < 6:
    exit(7)
git_cmd = argv[1]
git_dir = argv[2][1:-1]

if 'REBASE_USER' not in environ:
    exit(1)
user_id=int(environ['REBASE_USER'])

if git_cmd not in valid_commands:
    exit(2)
if not git_dir.startswith('/git'):
    exit(3)
if not exists(git_dir):
    exit(4)
user_ids_path = join(git_dir, '.git', 'authorized_users')
if not exists(user_ids_path):
    exit(5)

user_ids = []
authenticated = False
with open(user_ids_path, 'r') as f:
    for line in f:
        if int(line) == user_id:
            authenticated = True
            break

if not authenticated:
    exit(8)
original_cmd = [argv[1], argv[2][1:-1]]
call(original_cmd)
