version: '2'
volumes:
    log: {}
    sql: {}

services:
  rest_api:
    container_name: rest_api
    image: rest_api
    build: 
      context: ../services/rest_api
      dockerfile: Dockerfile.dev
      args:
        PYPI_SERVER_HOST:
        PYPI_SERVER_SCHEME:
        PYPI_SERVER_PORT:
    expose:
      - "5000"
    environment:
      REDIS_HOST: 'redis'
      RSYSLOG_HOST: 'logserver'
      RSYSLOG_PORT: 514
      DATABASE_HOST: 'database'
      API_URL_PREFIX: '/api/v1/'
      SECRET_KEY:
      GITHUB_APP_CLIENT_ID:
      GITHUB_APP_CLIENT_SECRET:
      CRAWLER_USERNAME:
      CRAWLER_PASSWORD:
      S3_BUCKET:
      BACKEND_AWS_ACCESS_KEY_ID:
      BACKEND_AWS_SECRET_ACCESS_KEY:
