version: '2'
volumes:
    log: {}
    sql: {}

services:
  api:
    container_name: api
    build: 
      context: ../services/api
      dockerfile: Dockerfile.dev
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ../services/api:/api
    environment:
      ALL_SERVICES_SETTINGS: ".dev"
      SETTINGS: ".web.dev"
      PYTHONHASHSEED: 2592602613
      FLASK_APP_SETTINGS: "/api/rebase/common/dev.py"
      S3_BUCKET:
      GITHUB_APP_ID:
      GITHUB_APP_SECRET:
      GITHUB_CODE2RESUME_ID:
      GITHUB_CODE2RESUME_SECRET:
