#!/bin/bash

pushd .

# let's activate the build virtual environment

source /venv/build/bin/activate

# First fetch wheel and build c extensions

pip wheel \
    --find-links /wheelhouse/wheels \
    --requirement docker/jupyter/requirements.txt \
    --wheel-dir=/wheelhouse/wheels

rm -rf /tmp/jupyter
mkdir -p /tmp/jupyter

python docker/jupyter/setup.py \
    build \
        -b /tmp/jupyter/build/ \
    bdist_wheel \
        -d /wheelhouse/wheels/ \
    egg_info \
        -e /tmp/jupyter

# Now let's make a Dockerfile context
# we can't symlink wheels into the 'source' directory 'docker/jupyter'
# because are not repeatable across machines and hence not supported by Docker.
# Instead, we just make hard copies of everything we need to build a container into a separate
# directory ('/tmp/jupyter'), build the container, and finally, wipe the build dir out.

cp docker/jupyter/pro-Dockerfile /tmp/jupyter/Dockerfile

cp docker/jupyter/cmd.bash /tmp/jupyter/cmd.bash

cp docker/jupyter/jupyter_notebook_config.py /tmp/jupyter/jupyter_notebook_config.py

cp rebase/common/pro.py /tmp/jupyter/flask.conf.py

cp -r /wheelhouse/wheels /tmp/jupyter/.

docker build -t rebase/pro-jupyter /tmp/jupyter

docker tag rebase/pro-jupyter alpha.rebaseapp.com:5000/rebase/pro-jupyter

rm -rf /tmp/jupyter

deactivate

popd
